// Move all large data structures outside the component
export const vietnameseProvinces = [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "TP Hồ Chí Minh",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
];

export const jobCategoriesMap = {
    "Academic/Education": "Học thuật/Giáo dục",
    "Accounting/Auditing": "Kế toán/Kiểm toán",
    "Administration/Office Support": "Hành chính/Hỗ trợ văn phòng",
    "Agriculture/Livestock/Fishery": "Nông nghiệp/Chăn nuôi/Thủy sản",
    "Architecture/Construction": "Kiến trúc/Xây dựng",
    "Art, Media & Printing/Publishing": "Nghệ thuật, Truyền thông & In ấn/Xuất bản",
    "Banking & Financial Services": "Ngân hàng & Dịch vụ tài chính",
    "CEO & General Management": "CEO & Quản lý chung",
    "Customer Service": "Dịch vụ khách hàng",
    Design: "Thiết kế",
    "Engineering & Sciences": "Kỹ thuật & Khoa học",
    "Food and Beverage": "Thực phẩm và Đồ uống",
    "Government/NGO": "Chính phủ/Tổ chức phi chính phủ",
    "Healthcare/Medical Services": "Chăm sóc sức khỏe/Dịch vụ y tế",
    "Hospitality/Tourism": "Khách sạn/Du lịch",
    "Human Resources/Recruitment": "Nhân sự/Tuyển dụng",
    "Information Technology/Telecommunications": "Công nghệ thông tin/Viễn thông",
    Insurance: "Bảo hiểm",
    Legal: "Pháp lý",
    "Logistics/Import Export/Warehouse": "Hậu cần/Xuất nhập khẩu/Kho bãi",
    Manufacturing: "Sản xuất",
    "Marketing, Advertising/Communications": "Marketing, Quảng cáo/Truyền thông",
    Pharmacy: "Dược phẩm",
    "Real Estate": "Bất động sản",
    "Retail/Consumer Products": "Bán lẻ/Sản phẩm tiêu dùng",
    Sales: "Bán hàng",
    Technician: "Kỹ thuật viên",
    "Textiles, Garments/Footwear": "Dệt may, May mặc/Giày dép",
    Transportation: "Vận tải",
    Others: "Khác",
};

export const experienceLevelsMap = {
    "Intern/Student": "Thực tập sinh/Sinh viên",
    "Fresher/Entry level": "Mới tốt nghiệp/Mới vào nghề",
    "Experienced (non-manager)": "Có kinh nghiệm (không phải quản lý)",
    Manager: "Quản lý",
    "Director and above": "Giám đốc trở lên",
};

export const experienceYearsMap = ["Chưa có kinh nghiệm", "1 năm", "2 năm", "3 năm", "4 năm", "5 năm", "6 năm", "7 năm", "8 năm", "9 năm", "10 năm", "Trên 10 năm"];

export const generateYearsList = () => {
    const currentYear = new Date().getFullYear();
    return Array.from({ length: 100 }, (_, i) => currentYear - i);
};
