export const metadata = {
    title: "JobNext | Bài viết việc làm",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <>{children}</>;
}
