export const metadata = {
    title: "JobNext | Phỏng vấn với AI",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <>{children}</>;
}
