import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import Header from "@/components/pageComponents/Header";
import Footer from "@/components/pageComponents/Footer";
import AuthContextProvider from "@/context/AuthContextProvider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "JobNext | Định hướng nghề nghiệp",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex flex-col items-center`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <AuthContextProvider>
                        <div className="max-w-[2200px] w-full flex flex-col items-center">
                            <Header />
                            {children}
                            <Footer />
                        </div>
                    </AuthContextProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
