import "./globals.css";
import localFont from "next/font/local";

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/pageComponents/Header";
import Footer from "@/components/pageComponents/Footer";
import AuthContextProvider from "@/context/AuthContextProvider";
import ProgressBar from "@/lib/ProgressBar";
import { ScrollArea } from "@/components/ui/scroll-area";
import QueryProvider from "@/context/QueryProvider";
const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "JobNext | Định hướng nghề nghiệp",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex flex-col items-center`}>
                <ScrollArea type="auto" className="h-screen w-full  flex flex-col justify-center items-center">
                    <ProgressBar>
                        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                            <AuthContextProvider>
                                <QueryProvider>
                                    <div className="max-w-[2200px] w-full flex flex-col items-center">
                                        <Header />
                                        {children}
                                        <Footer />
                                    </div>
                                </QueryProvider>
                                <Toaster position="bottom-right" richColors closeButton />
                            </AuthContextProvider>
                        </ThemeProvider>
                    </ProgressBar>
                </ScrollArea>
            </body>
        </html>
    );
}
