import { JobProvider } from "@/context/JobProvider";
export const metadata = {
    title: "JobNext | Việc làm",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {
    return <JobProvider> {children}</JobProvider>;
}
