export const metadata = {
    title: "JobNext | Chuẩn bị phỏng vấn",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <>{children}</>;
}
