export const metadata = {
    title: "JobNext | Phân tích - gợi ý chỉnh sửa - tạo CV",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <> {children}</>;
}
