import "./globals.css";

import AuthContextProvider from "@/context/AuthContextProvider";

export const metadata = {
    title: "JobNext | Tạo CV",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={` antialiased w-full `}>
                <AuthContextProvider>{children}</AuthContextProvider>
            </body>
        </html>
    );
}
